PUT http://localhost:3001/api/readinglists/1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1eWh1eW5oIiwiaWQiOjEsImlhdCI6MTcxNjA0MTYzNH0.rpYBaqHabty3Gtmmq0zwNj46G7OG6gciA94BwxXFl2U

{
    "read": true 
}

###
PUT http://localhost:3001/api/readinglists/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1eWh1eW5oIiwiaWQiOjEsImlhdCI6MTcxNjA0MTYzNH0.rpYBaqHabty3Gtmmq0zwNj46G7OG6gciA94BwxXFl2U

{
    "read": false 
}